empleo_proj:
  outputs:
    dev:
      dataset: prueba_1
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: \Users\ignac\.dbt\dbt-user-creds.json
      location: US
      method: oauth
      priority: interactive
      project: cloud-run-dbt-test1
      threads: 3
      type: bigquery
  target: dev
